language: node_js

cache: npm

notifications:
  email: false

node_js:
  - 12

install: npm ci

script:
  - npm run coverage
  - npm run build

after_success: npx codecov

branches:
  only:
    - master
    - next

jobs:
  # Define the release stage that runs semantic-release
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        script:
          - npx semantic-release@17
